name: psych_ai
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  ionicons: ^0.2.2
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  http: ^1.1.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/

 
  fonts:
    - family: Baloo Da
      fonts:
        - asset: assets/fonts/BalooDa2-Bold.ttf
        - asset: assets/fonts/BalooDa2-ExtraBold.ttf
        - asset: assets/fonts/BalooDa2-Regular.ttf
  